// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiUICHA07IbOXeoYKve03gRdWjnbJkDqI',
    appId: '1:216524050605:web:c35af2ccf42e59cf183624',
    messagingSenderId: '216524050605',
    projectId: 'ecommerce-91d69',
    authDomain: 'ecommerce-91d69.firebaseapp.com',
    storageBucket: 'ecommerce-91d69.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJADd7cJX8Z708QNSsYdXceheD1TRISYY',
    appId: '1:216524050605:android:f53783492d5ba7f2183624',
    messagingSenderId: '216524050605',
    projectId: 'ecommerce-91d69',
    storageBucket: 'ecommerce-91d69.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_9CdIldpG9uFWsY0q53ZwC_dVy1g9Nuo',
    appId: '1:216524050605:ios:5b547ff1f4f8849c183624',
    messagingSenderId: '216524050605',
    projectId: 'ecommerce-91d69',
    storageBucket: 'ecommerce-91d69.appspot.com',
    androidClientId: '216524050605-g5cacr17urkupperce9etquhlogfbh6a.apps.googleusercontent.com',
    iosClientId: '216524050605-mf6cbhk1nvo9ilr9lk2i13hkgcj7hk7q.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_9CdIldpG9uFWsY0q53ZwC_dVy1g9Nuo',
    appId: '1:216524050605:ios:6846b4ddb9a87cf5183624',
    messagingSenderId: '216524050605',
    projectId: 'ecommerce-91d69',
    storageBucket: 'ecommerce-91d69.appspot.com',
    androidClientId: '216524050605-g5cacr17urkupperce9etquhlogfbh6a.apps.googleusercontent.com',
    iosClientId: '216524050605-vn7dpvjp39jalodggs97sn73hr4floae.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceApp.RunnerTests',
  );
}
